spring:
  application:
    name: backend

  # 1. DB 연결 설정 (도커 MySQL과 통신)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buffett_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: buffett_user
    password: userpassword123!

  # 2. JPA 설정 (자바와 DB 자동 연결)
  jpa:
    hibernate:
      ddl-auto: update # 엔티티를 보고 테이블을 자동 수정하도록. 초반에 임시로
    show-sql: true # 백엔드가 DB로 날리는 SQL을 터미널에 보여줌
    properties:
      hibernate:
        format_sql: true # SQL을 예쁘게 줄바꿈해서 보여줌